management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081
spring:
  datasource:
    username: root
    password: 102535@Yile
    url: jdbc:mysql://localhost:3306/account_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.huawei.account.cseaccountservice.entity
  configuration:
    map-underscore-to-camel-case: true # 配置 数据库 下划线映射 驼峰命名法
    cache-enabled: false


eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8081
    non-secure-port-enabled: true
    ip-address: 127.0.0.1
