 # 加解密根密码
jasypt:
  encryptor:
    password: ${xxx:testtt} #根密码
# redis 相关
spring:
  redis:
    password: redis@123456
    host: shycloud-redis
    port: 6579
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  # zipkin
  zipkin:
    enabled: true
    base-url: http://shycloud-zipkin
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      # 默认的采样比率为0.1，不能看到所有请求数据
      # 更改采样比率为1，就能看到所有的请求数据了，但是这样会增加接口调用延迟
      probability: 1.0

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
# hystrix If you need to use ThreadLocal bound variables in your RequestInterceptor`s
# you will need to either set the thread isolation strategy for Hystrix to `SEMAPHORE or disable Hystrix in Feign.
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true

#swagger公共信息
swagger:
  host: shycloud-gateway:9999
  title: Shycloud Swagger API
  description: Spring Cloud微服务开发脚手架
  version: 2.5
  license: Powered By shycloud
  licenseUrl: https://shycloud.com/
  terms-of-service-url: https://shycloud.com/
  contact:
    name: npm
    email: hzchen@360tec.com
    url: https://shycloud.com/about.html
  authorization:
    name: shycloud OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://shycloud-gateway:9999/auth/oauth/token

## spring security 配置
security:
  oauth2:
    client:
      # 默认放行url,如果子模块重写这里的配置就会被覆盖
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /collection/selectbysyid
        - /webapi/*
        - /train/aliPayNotifyUrl
        - /train/wxNotify
        - /move/aliPayNotifyUrl
        - /move/wxNotify
        - /v1/mobile/wxNotify
        - /v1/mobile/aliNotify
        - /v1/mobile/register/*
        - /v1/mobile/info/*
        - /v1/mobile/load/*
        - /v1/mobile/send/*
        - /member/memberList/*
    resource:
      loadBalanced: true
      token-info-uri: http://shycloud-auth/oauth/check_token
