logging:
  config: classpath:logback-spring.xml
  level.org.springframework.boot.autoconfigure: error
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    enabled: true      