management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8086
spring:
  application:
    name: customer-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    non-secure-port: 8086
    non-secure-port-enabled: true
    ip-address: 127.0.0.1
