management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 102535@Yile
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.huawei.user.cseuserservice.entity
  configuration:
    map-underscore-to-camel-case: true # 配置 数据库 下划线映射 驼峰命名法
    cache-enabled: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    non-secure-port: 8082
    non-secure-port-enabled: true
    ip-address: 127.0.0.1
