management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9090
spring:
  application:
    name: zuul-service

logging:
  config: classpath:logback-spring.xml
  level.org.springframework.boot.autoconfigure: error

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    non-secure-port: 9090
    non-secure-port-enabled: true
    ip-address: 127.0.0.1
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  sensitive-headers:
  add-host-header: true
  routes:
    user:
      path: /user/**
      service-id: user-service
    hystrix:
      path: /hystrix/**
      service-id: hystrix-dashboard
    customer:
      path: /customer/**
      service-id: customer-service
    account:
      path: /account/**
      service-id: account-service
    product:
      path: /product/**
      service-id: product-service
    config:
      path: /config/**
      service-id: config-server
